[cpu]
core=dynamic

cycles=max

turbo=true

[autoexec]
# Mounting otomatis folder MMPI2007 sebagai Drive C.
# {MMPI_DIR} diganti otomatis oleh server.py dengan lokasi server/vDosMMPI/MMPI2007 di komputer ini.
MOUNT C "{MMPI_DIR}"
C:
# Langsung jalankan programnya
MMPI.EXE
# (Opsional) Langsung exit jika program ditutup, supaya server tau proses selesai
#EXIT
