[cpu]
core=dynamic

cycles=max

turbo=true

[autoexec]
# Mounting otomatis folder project Anda sebagai Drive C
MOUNT C C:\Users\User\Documents\Coding\Website\MMPI\server\vDosMMPI\MMPI2007
C:
# Langsung jalankan programnya
MMPI.EXE
# (Opsional) Langsung exit jika program ditutup, supaya server tau proses selesai
#EXIT
